name: Dockerized Django CI 

on:
  push:
    branches: [dev, features, release, hotfix]
  pull_request:
    branches: [dev, features, release, hotfix, main]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file for CI
        run: |
          echo "SECRET_KEY=i_see_you_like_to_read_others_code_huh" >> .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=*" >> .env
          echo "POSTGRES_USER=test_user" >> .env
          echo "POSTGRES_PASSWORD=test_password" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "POSTGRES_DB=test_db" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "CHAPA_SECRET_KEY=24" >> .env
          echo "BACKEND_CALLBACK_URL=23" >> .env
          echo "FRONTEND_RETURN_URL=22" >> .env

      - name: Build & Start Services
        run: docker compose -f compose.yaml -f compose.dev.yaml up --build -d

      - name: Run Migrations
        run: docker compose exec -T web python manage.py migrate
      
      - name: Run Tests
        run: docker compose -f compose.yaml -f compose.dev.yaml run --rm web pytest

      - name: Stop Services
        if: always()
        run: docker compose down -v

